### ISSUE TITLE
Bundle load error callback?

### ISSUE THREAD

**Issue by raphaelluchini** [webpack-contrib/bundle-loader#13]
Hello, I've developing an async application and I am getting some problems with deploys and hash.chunks while the user is interacting in the website, I tough was possible to get error callback in loaders, but I didn't figure out. Is it possible to create this feature?

var load = require("bundle?lazy!./file.js");
load(function(file) {

}, function(err){

});

**Comment by exdis** [comment]
+1

**Comment by isstaif** [comment]
Is there anyway to handle network errors?

**Comment by richardscarrott** [comment]
I believe webpack 2 will include support for [error handling via `System.import`](https://github.com/webpack/webpack/pull/785#issuecomment-111965957) and in turn the bundle loader could easily be updated to proxy through.

In the meantime I added support through a plugin https://github.com/richardscarrott/require-error-handler-webpack-plugin

**Comment by NekR** [comment]
Hi guys, here I made little loader based on ``bundle-loader`` but with error handling improvements: https://github.com/NekR/async-module-loader

Hope it will help, it's just a bit minimalistic than including a lot of custom plugins and can replace ``bundle-loader`` just with few modifications.

**Comment by NekR** [comment]
Okay, now I updated loader to properly clear pending callbacks when loading fails so file can be properly requested again. This also eliminates possible memory leaks with uncleared pending callbacks.

**Comment by moshemal** [comment]
+1

**Comment by denich** [comment]
+1

**Comment by psacc** [comment]
+1

**Comment by codymullins** [comment]
+1

**Comment by sdhhqb** [comment]
+1

**Comment by djyde** [comment]
why it was closed?

**Comment by vicvinc** [comment]
need to do some thine when webpack load chunk failed...
