### ISSUE TITLE
Error with json loader

### ISSUE THREAD

**Issue by nkovacs** [webpack-contrib/bundle-loader#16]
Install cldr-data and json-loader

```
npm install cldr-data json-loader
```

Add this to the config:

```
{ test: /\.json$/, loader: "json" },
```

And then try this:

``` js
require([
    'bundle?name=[path]!cldr-data/main/' + locale + '/numbers.json',
    'bundle?name=[path]!cldr-data/main/' + locale + '/ca-gregorian.json',
    'bundle?name=[path]!cldr-data/main/' + locale + '/timeZoneNames.json'
], function(a, b, c) {
});
```

This combines all the jsons in one locale directory into a single chunk, which is good. Unfortunately, the chunk looks like this:

```
webpackJsonp([150],{

/***/ 394:
/***/ function(module, exports) {

    module.exports = {
```

And I get the following error:

Uncaught json: E_INVALID_PAR_TYPE: {"expected":"Plain Object","name":"json"}

**Comment by nkovacs** [comment]
Actually, it's not an error with the json loader, it looks like bundle can't be used with the require([]) syntax.

I fixed it like this:

```
(require('bundle?name=[path]!cldr-data/main/' + locale + '/numbers.json'))(cb)
(require('bundle?name=[path]!cldr-data/main/' + locale + '/ca-gregorian.json'))(cb)
(require('bundle?name=[path]!cldr-data/main/' + locale + '/timeZoneNames.json'))(cb)
```

**Comment by michael-ciniawsky** [comment]
@nkovacs Please provide more info about your current setup (`webpack.config.js` etc), did you found a solution for this ?
