### ISSUE TITLE
emoji table

### ISSUE THREAD

**Issue by pwnsdx** [webpack-contrib/bundle-loader#29]
Hello,

This plugin is great at its job, unfortunately it requires loader-utils which requires emojis-list so I was somehow surprised that this plugin added the whole emoji table in my JS code as a dependency. Is there any way to prevent this apart from forking your repository and deleting the loader-utils dependency?

Regards,

**Comment by michael-ciniawsky** [comment]
@pwnsdx Did you try without `loader-utils` and need to take a look at the code first if that's possible, but out of the gut I would say no, because `loader-utils` is used by most of the loaders and will be added anyways

**Comment by pwnsdx** [comment]
This repo is using some functions of loader-utils so I can't use it without.

Anyway, I'm using System.Import/import so I think this repository is no longer useful nowadays.

Regards,
