### ISSUE TITLE
[Bug] name parameter is completely ignored

### ISSUE THREAD

**Issue by ArtemZag** [webpack-contrib/bundle-loader#39]
I tried to use different options. But it's simply ignored.
Maybe the reason is that I use webpack 2.

**Comment by michael-ciniawsky** [comment]
@ArtemZag Cpuld you please provide more info about your setup (`webpack.config.js` etc) ?

**Comment by ArtemZag** [comment]
@michael-ciniawsky I didn't configure bundle-loader in webpack config. I just used require function.
Like this: 
`const momentLocaleFile = require('bundle-loader?name=[path][name].[ext]?[hash]&lazy!moment/locale/' + momentLocale);`

**Comment by michael-ciniawsky** [comment]
@ArtemZag So it is solved or still any regressions? 😛 Especially in regard to webpack 2 compatibility :)

**Comment by ArtemZag** [comment]
@michael-ciniawsky , sorry for late answer. Yes, the parameter is still ignored (using webpack 2).
After the build I just get files like "1.js", "2.js" and so on.
Like this:
![image](https://cloud.githubusercontent.com/assets/1687370/25189877/339efe48-2533-11e7-98f5-4ca9fac480f8.png)

**Comment by wisdomofgod** [comment]
The reason for this may be that webpack didn't find require. ensure function

**Comment by mikegleasonjr** [comment]
Same thing here...

rule: 

```
{
    test: /froala.js$/,
    include: [path.resolve(__dirname, 'src')],
    use: [{ loader: 'bundle-loader', options: { name: 'froala' } }],
},
```

output:

```
output: {
    path: path.resolve(__dirname, 'build'),
    filename: `[name].[chunkhash:6].${suffix}.js`,
    publicPath: '/',
},
```

The result is always something like `build/0.82e16f.min.js`.

**Comment by ArtemZag** [comment]
Tested with the last bundle-loader version. Now it works normally.
