### ISSUE TITLE
[documentation] FLow

### ISSUE THREAD

**Issue by sapottier** [webpack-contrib/bundle-loader#55]
Hello,

To use bundle-loader with Flow, you have to put into .flowconfig this option :

`module.name_mapper='^bundle-loader\?lazy!\(.*\)$' -> '\1'`

Hope this will help

**Comment by evilebottnawi** [comment]
@sapottier why your need flow here? can your provide example use case?

**Comment by sapottier** [comment]
A small example who return 'Required module not fund' without the option.

`
// @flow

type routes = Array<{
  path: string,
  content: any, 
  header?: any,
  sidebar?: any,
  default?: boolean,
  restricted?: boolean | Array<string>,
  routes?: routes
}>;

import Example from 'bundle-loader?lazy!../views/Example/Example';
import Of from 'bundle-loader?lazy!../views/Of/Of';
import NestedRoute from 'bundle-loader?lazy!../views/NestedRoute/NestedRoute';

export const routerConfig: routes = [{
  path: '',
  content: Example,
  routes: [
    {
      path: 'example',
      content: Example,
      routes: [
        {
          path: 'of',
          content: Of,
          routes: [
            {
              path: 'nested-route',
              content: NestedRoute
            }
          ]
        }
      ]
    }
  ]
}];

`

**Comment by evilebottnawi** [comment]
@sapottier What do you expect and what do you get?

**Comment by sapottier** [comment]
Sorry, I have to be more precise. (sorry for my english)

Everything works well, except that when we use Flow, It does not understand 'bundle-loader?lazy!…' and return un error like 'Required module not fund'. To bypass this, a simple way is to configure Flow like previously explain. Also, maybe there is more to do by providing a flow-typed definition.

thank you,

Simon

**Comment by dignifiedquire** [comment]
Thanks, helped me!

**Comment by fabiomcosta** [comment]
Given you can also give a name to the bundle (ex: `'bundle-loader?lazy&name=bundle-name!./path`), a more correct regexp would be:
```
module.name_mapper='^bundle-loader\?lazy[^!]*!\(.*\)$' -> '\1'
```
