### ISSUE TITLE
Named chunks

### ISSUE THREAD

**Issue by nickdima** [webpack-contrib/bundle-loader#6]
@sokra as per our discussion [here](https://github.com/webpack/webpack/issues/441#issuecomment-55408136) I'm working on implementing the `name` parameter.
I think it should work for both regular and dynamic requires. For dynamic requires it should be a regex that extracts the name from the filename being processed. A few questions: 
- should I use the same `name` parameter for both and detect in some way if it's a plain string or regular expresion? or better to use different parameters?  Any examples of loaders that use regex in the query?
- is it safe to suppose that the filename is always the last part of `remainingRequest`?

**Comment by BowlingX** [comment]
Hi,

is this implemented in the bundle-loader? I tried to do the following.

```
require(
      `bundle?name=moment_local_[name]!moment/locale/${locale}.js`
    )
```

It will require all locale files, but just creates one bundle with all modules inside. The Name of the module is `moment_locale_firstLocaleFound`. So, [name] is replaced, but not dynamically for each file but just for the first file required. I was expecting it creates one bundle for each included file.

**Comment by bora89** [comment]
@BowlingX 
for me it is worked:
```Javascript
require(`bundle?name=[name].settings.lang!./lang/${locale}.json`)
```

I got separate files for each of my translated languages like these:
`1.en.settings.lang.js`
`2.ru.settings.lang.js`
which are included separetelly

**Comment by dlangerenken** [comment]
I'm still seeing this issue that `require(`bundle-loader?name=[name]&lazy!./resources/nls/${lang}/localeElements`);` is only creating one chunk
