### ISSUE TITLE
bundle not found

### ISSUE THREAD

**Issue by roycehaynes** [webpack-contrib/bundle-loader#9]
I installed bundle-loader from npm and it says it's not found. I've verified the package is in my node_modules dir. I'm installing version 0.5.1.

```
var PreDashboard = React.createClass({
  mixins: [AsyncReactComponent],
  bundle: require('bundle?lazy!./Dashboard.react.js'),
  preRender: function() {
    return <div>Loading dashboard...</div>
  }
});
```

**Comment by michael-ciniawsky** [comment]
@roycehaynes Please provide more info about your current setup (`webpack.config.js` etc), did you solve the issue ?

**Comment by roycehaynes** [comment]
@michael-ciniawsky - This is no longer an issue.
